name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

categories:
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'

  - title: '🚀 Features'
    when:
      labels:
        - 'feature'
        - 'enhancement'
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - 'fix'
        - 'bug'
  - title: '🧰 Maintenance'
    when:
      labels:
        - 'chore'
        - 'dependencies'
        - 'refactor'
  - title: '📝 Documentation'
    when:
      labels:
        - 'documentation'

  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      label: 'major'
  - type: 'version-resolver'
    semver-increment: 'minor'
    when:
      labels:
        - 'minor'
        - 'feature'
        - 'enhancement'
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      labels:
        - 'patch'
        - 'fix'
        - 'bug'
        - 'chore'
        - 'dependencies'
        - 'refactor'

version-resolver:
  default: patch

template: |
  ## What's Changed

  $CHANGES
